import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'

const PILLARS = [
  {h:"Market Penetration",b:"Disrupting a saturated snacking category required shifting away from muted, clinical aesthetics. The goal was to establish raw consumer connection within seconds of retail exposure."},
  {h:"MOM Bar Campaign",b:"Developing an intensive promotional strategy and campaign structure for the Amazon channel launch of the premium MOM Bar product lines."},
  {h:"Volume Scaling",b:"Constructing visual frameworks capable of supporting rapid volume surges — moving from initial low-run test batches into massive industrial commercial production loops."},
  {h:"The Halo Effect",b:"Engineering the bar packaging system to function as a visual entry point for the brand — driving organic consumer interest and cross-category discovery across the rest of the company portfolio."},
]
const FEEDBACK = [
  {n:"Shilpa Moglishetty",r:"Co-Founder, Campaign Director",q:"The MOM Bar promotional strategy aligned perfectly with our fundraising goals, positioning the range as a core category anchor.",c:"leadership"},
  {n:"Roshan Kulranjan",r:"Business Operations Head",q:"The visual system handled the rapid scale shift seamlessly, supporting our transition from 250 units to massive retail supply lines without friction.",c:"team"},
]
const CSS = `
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--br-bg:#0A0906;--br-white:#F0EDE6;--br-accent:#FF3366;--br-muted:rgba(240,237,230,0.45);--br-border:rgba(240,237,230,0.08);--br-glass:rgba(240,237,230,0.03);--D:'Doto',sans-serif;--S:'Poppins',sans-serif;--M:'Space Mono',monospace}
html{scroll-behavior:smooth}body{background:var(--br-bg);color:var(--br-white);font-family:var(--S);overflow-x:hidden}a{color:inherit;text-decoration:none}
.br-nav{position:fixed;top:0;left:0;right:0;z-index:100;display:flex;align-items:center;justify-content:space-between;padding:1.2rem 5vw;background:rgba(10,9,6,0.8);backdrop-filter:blur(20px);border-bottom:1px solid var(--br-border)}
.br-logo{font-family:var(--D);font-size:1.3rem;letter-spacing:.08em}.br-back{font-family:var(--M);font-size:.6rem;letter-spacing:.2em;padding:.55rem 1.4rem;border:1px solid var(--br-border);border-radius:40px;transition:.3s}.br-back:hover{border-color:var(--br-accent);color:var(--br-accent)}
.br-hero{min-height:100vh;display:flex;align-items:flex-end;position:relative;overflow:hidden;border-bottom:1px solid var(--br-border)}
.br-hero-bg{position:absolute;inset:0;background:radial-gradient(ellipse at 30% 75%,rgba(255,51,102,0.18),transparent 55%),radial-gradient(ellipse at 75% 25%,rgba(255,51,102,0.06),transparent 55%),var(--br-bg);animation:brPulse 10s ease-in-out infinite}
@keyframes brPulse{0%,100%{opacity:.85}50%{opacity:1}}
.br-hero-inner{position:relative;z-index:2;padding:0 5vw 5rem;width:100%}
.br-hero-tag{font-family:var(--M);font-size:.6rem;letter-spacing:.25em;color:var(--br-accent);margin-bottom:2rem}
.br-hero h1{font-family:var(--D);font-size:clamp(5rem,14vw,14rem);line-height:.85}.br-hero h1 span{color:var(--br-accent)}
.br-hero h1 em{font-style:normal;color:var(--br-muted);font-family:var(--S);font-weight:300;display:block;font-size:.32em;margin-top:1rem;line-height:1.6;max-width:580px}
.br-c{max-width:1200px;margin:0 auto;padding:0 5vw}.br-s{padding:8rem 0;border-bottom:1px solid var(--br-border)}
.br-label{font-family:var(--M);font-size:.58rem;letter-spacing:.22em;color:var(--br-accent);margin-bottom:1.5rem}
.br-title{font-family:var(--D);font-size:clamp(2.8rem,6vw,6.5rem);line-height:.9;margin-bottom:2.5rem}.br-title em{font-style:normal;color:var(--br-muted);font-family:var(--S);font-weight:300}
.br-body{font-size:1.1rem;line-height:1.9;color:var(--br-muted);max-width:640px}
.br-pillars{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--br-border);min-height:80vh}
.br-pill-left{position:sticky;top:0;height:100vh;display:flex;flex-direction:column;justify-content:center;padding:4rem;background:var(--br-bg)}
.br-pill-right{display:flex;flex-direction:column}
.br-pill-card{background:var(--br-bg);padding:4rem;border-bottom:1px solid var(--br-border);min-height:50vh;display:flex;flex-direction:column;justify-content:center;position:relative;overflow:hidden}
.br-pill-card::after{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(255,51,102,0.08),transparent 70%);opacity:0;transition:.4s;pointer-events:none}.br-pill-card:hover::after{opacity:1}
.br-pill-card h3{font-family:var(--D);font-size:clamp(2rem,4vw,4rem);margin-bottom:1.5rem}.br-pill-card p{font-size:1.05rem;line-height:1.9;color:var(--br-muted);max-width:520px}
.br-dash{display:grid;grid-template-columns:1fr 1fr;gap:4rem;align-items:start}
.br-kpi{background:var(--br-glass);border:1px solid var(--br-border);padding:2rem;margin-bottom:1rem;position:relative;overflow:hidden}.br-kpi::after{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(255,51,102,0.08),transparent 70%);opacity:0;transition:.4s;pointer-events:none}.br-kpi:hover::after{opacity:1}.br-kpi p{font-size:.95rem;line-height:1.8;color:var(--br-muted)}
.br-metric-card{background:var(--br-bg);border:2px solid var(--br-accent);padding:2.5rem;text-align:center;position:relative;overflow:hidden;margin-bottom:1.5rem}
.br-metric-card::before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(255,51,102,0.1),transparent 70%)}
.br-metric-n{font-family:var(--D);font-size:clamp(3.5rem,7vw,6rem);color:var(--br-accent);line-height:1;position:relative}.br-metric-l{font-family:var(--M);font-size:.5rem;letter-spacing:.15em;color:var(--br-muted);margin-top:.8rem;position:relative;line-height:1.7}
.br-soul{background:rgba(255,51,102,0.02);padding:10rem 0;text-align:center}
.br-soul-q{font-family:var(--S);font-size:clamp(1.15rem,2vw,1.7rem);line-height:2;color:var(--br-muted);max-width:780px;margin:0 auto;font-weight:300}.br-soul-q strong{color:var(--br-white);font-weight:500}
.br-gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--br-border)}.br-gal-item{background:var(--br-glass);aspect-ratio:4/3;display:flex;align-items:center;justify-content:center;font-family:var(--D);font-size:.7rem;letter-spacing:.12em;color:rgba(240,237,230,0.08);transition:background .3s}.br-gal-item:hover{background:rgba(255,51,102,0.06)}
.br-fb-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1px;background:var(--br-border);border:1px solid var(--br-border)}.br-fb-card{background:var(--br-bg);padding:2.5rem;display:flex;flex-direction:column;gap:1.2rem;position:relative;overflow:hidden}.br-fb-card::after{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(255,51,102,0.08),transparent 70%);opacity:0;transition:.4s;pointer-events:none}.br-fb-card:hover::after{opacity:1}
.br-fb-q{font-size:1rem;line-height:1.85;color:var(--br-muted);font-style:italic;flex:1}.br-fb-n{font-family:var(--D);font-size:1.1rem}.br-fb-r{font-family:var(--M);font-size:.5rem;letter-spacing:.18em;color:var(--br-accent);margin-top:.15rem}
.br-footer{padding:4rem 0 2.5rem;border-top:1px solid var(--br-border)}.br-footer-links{display:flex;flex-wrap:wrap;gap:2rem;margin:2rem 0 3rem}.br-footer-link{font-family:var(--D);font-size:clamp(1.4rem,3vw,2.2rem);color:var(--br-muted);transition:color .3s}.br-footer-link:hover{color:var(--br-accent)}
.br-footer-meta{display:flex;justify-content:space-between;font-family:var(--M);font-size:.5rem;letter-spacing:.15em;color:rgba(240,237,230,0.25);padding-top:2rem;border-top:1px solid var(--br-border)}
.brv{opacity:0;transform:translateY(24px);transition:opacity .8s cubic-bezier(.16,1,.3,1),transform .8s cubic-bezier(.16,1,.3,1)}.brv.vis{opacity:1;transform:translateY(0)}
@media(max-width:900px){.br-pillars{grid-template-columns:1fr}.br-pill-left{position:relative;height:auto;padding:3rem 2rem}.br-pill-card{padding:3rem 2rem;min-height:auto}.br-dash{grid-template-columns:1fr;gap:2rem}.br-gallery{grid-template-columns:1fr 1fr}.br-fb-grid{grid-template-columns:1fr}.br-footer-meta{flex-direction:column;gap:.8rem}}
@media(max-width:540px){.br-hero h1{font-size:clamp(3.5rem,16vw,8rem)}.br-s{padding:5rem 0}.br-soul{padding:6rem 0}.br-gallery{grid-template-columns:1fr}}
`
const NAV = ['Core Packaging','Superfoods','Brand Guidelines','Jars','Snacks','Marketing','Management']
export default function Bars(){return(<>
<Head><meta charSet="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Bars Portfolio — Sivnco</title><meta name="description" content="High-velocity retail dashboard — snack bar category scaling and MOM Bar campaign."/><link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/><link href="https://fonts.googleapis.com/css2?family=Doto:wght@100..900&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400;1,600&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet"/><style dangerouslySetInnerHTML={{__html:CSS}}/></Head>
<Script src="https://unpkg.com/@studio-freight/lenis@1.0.32/dist/lenis.min.js" strategy="afterInteractive"/>
<nav className="br-nav"><Link href="/" className="br-logo">SIVNCO<span style={{color:'var(--br-accent)'}}>.</span></Link><Link href="/jusamazin" className="br-back">← Case Study</Link></nav>
<div className="br-hero"><div className="br-hero-bg"/><div className="br-hero-inner"><div className="br-hero-tag">Category Scaling / Volume Expansion</div><h1>Snack<br/><span>Bars</span><em>Disrupting the saturated snacking category with maximum visual velocity. From 250 units to 8,000 monthly — design as a revenue engine.</em></h1></div></div>
<section className="br-s" style={{padding:0,borderBottom:'none'}}><div className="br-pillars"><div className="br-pill-left"><div className="br-label brv">Strategy</div><div className="br-title brv">Retail<br/><em>Velocity.</em></div><p className="br-body brv">The strategic engine behind scaling a snack bar portfolio from test batches to high-volume commercial production.</p></div><div className="br-pill-right">{PILLARS.map((p,i)=>(<div key={i} className="br-pill-card brv"><div className="br-label">{`0${i+1}`}</div><h3>{p.h}</h3><p>{p.b}</p></div>))}</div></div></section>
<section className="br-s"><div className="br-c"><div className="br-label brv">Impact</div><div className="br-title brv">Revenue &amp;<br/><em>Volume.</em></div><div className="br-dash"><div><p className="br-body brv" style={{marginBottom:'2rem'}}>Direct financial contribution of the snack bars category to the overarching corporate balance sheet, alongside rapid escalation of monthly product movement.</p><div className="br-kpi brv"><p>Rapid escalation of monthly product movement across core digital channels.</p></div><div className="br-kpi brv"><p>Direct financial contribution driving rapid discoverability across parallel brand portfolios — the Bar Halo Effect.</p></div></div><div style={{display:'flex',flexDirection:'column',gap:'1.5rem'}}><div className="br-metric-card brv"><div className="br-metric-n">34%</div><div className="br-metric-l">Overall contribution to total brand revenue in the 2024-25 cycle</div></div><div className="br-metric-card brv"><div className="br-metric-n">250→8K</div><div className="br-metric-l">Monthly unit production scale expansion</div></div></div></div></div></section>
<div className="br-soul"><div className="br-c"><div className="br-label brv" style={{textAlign:'center'}}>Category Disruption Thesis</div><blockquote className="br-soul-q brv">&ldquo;Commercial snack design cannot afford to be passive. It must operate at <strong>maximum visual volume</strong> on the shelf, turning raw color contrast and typographic weight into <strong>immediate retail velocity</strong>.&rdquo;</blockquote></div></div>
<section className="br-s" style={{padding:0}}><div className="br-gallery">{['STUDIO MACRO','AMAZON CAMPAIGN','STORE PLACEMENT','MOM BAR HERO','VARIANT LINEUP','SHELF DISPLAY'].map(g=>(<div key={g} className="br-gal-item brv">{g}</div>))}</div></section>
<section className="br-s"><div className="br-c"><div className="br-label brv">Voices</div><div className="br-title brv">Feedback<br/><em>Matrix.</em></div><div className="br-fb-grid">{FEEDBACK.map((fb,i)=>(<div key={i} className="br-fb-card brv"><div className="br-fb-q">&ldquo;{fb.q}&rdquo;</div><div><div className="br-fb-n">{fb.n}</div><div className="br-fb-r">{fb.r}</div></div></div>))}</div></div></section>
<div className="br-c"><div className="br-footer"><div className="br-label">Category Index {'>>>'}</div><div className="br-footer-links">{NAV.map(l=>(<Link key={l} href="/jusamazin" className="br-footer-link">{l}</Link>))}</div><div className="br-footer-meta"><span>© 2023–2026</span><span>My Journey @ Jus&apos;Amazin</span></div></div></div>
<Script id="br-init" strategy="lazyOnload">{`(function(){function init(){var obs=new IntersectionObserver(function(e){e.forEach(function(e){if(e.isIntersecting){e.target.classList.add('vis');obs.unobserve(e.target)}})},{threshold:.05});document.querySelectorAll('.brv').forEach(function(e){obs.observe(e)});setTimeout(function(){document.querySelectorAll('.brv').forEach(function(e){e.classList.add('vis')})},2000);if(window.innerWidth<=900)document.querySelectorAll('.brv').forEach(function(e){e.classList.add('vis')})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();(function w(){if(typeof Lenis==='undefined'){setTimeout(w,80);return}try{var l=new Lenis({duration:1.2,smooth:true,smoothTouch:false});function r(t){l.raf(t);requestAnimationFrame(r)}requestAnimationFrame(r)}catch(e){}})()})();`}</Script>
</>)}
