import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'

const PILLARS = [
  {h:"MOM2B Architecture",b:"Developing the comprehensive digital infographic and asset rollout for the premium Mom2B (M2B) Almond & Seed Butter range."},
  {h:"Material Splitting",b:"Managing design parameters across two completely distinct packaging lines, requiring specialized asset optimization for both Glass Jars and Plastic Jars."},
  {h:"Channel Target Mapping",b:"Tailoring rendering workflows to align with specific distribution channels — Glass Jars targeting high-end premium retail, Plastic Jars optimized for fast D2C shipping logistics."},
  {h:"System Sync",b:"Maintaining strict data and font synchronization across independent asset generation pipelines to ensure a uniform brand message across platforms."},
]
const FEEDBACK = [
  {n:"Juhi Singh",r:"Visual Design Colleague",q:"Splitting the infographic workflows into distinct directory tracks allowed us to optimize the material stories for both the glass and plastic packaging without overlapping files."},
  {n:"Roshan Kulranjan",r:"Logistics & Operations Head",q:"The asset segregation matched our physical inventory models perfectly, making platform uploads quick and predictable."},
]
const CSS = `
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--jr-bg:#0A0906;--jr-white:#F0EDE6;--jr-accent:#C0A060;--jr-silver:#A0AEB8;--jr-muted:rgba(240,237,230,0.45);--jr-border:rgba(240,237,230,0.08);--jr-glass:rgba(240,237,230,0.03);--D:'Doto',sans-serif;--S:'Poppins',sans-serif;--M:'Space Mono',monospace}
html{scroll-behavior:smooth}body{background:var(--jr-bg);color:var(--jr-white);font-family:var(--S);overflow-x:hidden}a{color:inherit;text-decoration:none}
.jr-nav{position:fixed;top:0;left:0;right:0;z-index:100;display:flex;align-items:center;justify-content:space-between;padding:1.2rem 5vw;background:rgba(10,9,6,0.8);backdrop-filter:blur(20px);border-bottom:1px solid var(--jr-border)}
.jr-logo{font-family:var(--D);font-size:1.3rem;letter-spacing:.08em}.jr-back{font-family:var(--M);font-size:.6rem;letter-spacing:.2em;padding:.55rem 1.4rem;border:1px solid var(--jr-border);border-radius:40px;transition:.3s}.jr-back:hover{border-color:var(--jr-accent);color:var(--jr-accent)}
.jr-hero{min-height:100vh;display:flex;align-items:flex-end;position:relative;overflow:hidden;border-bottom:1px solid var(--jr-border)}
.jr-hero-bg{position:absolute;inset:0;background:radial-gradient(ellipse at 30% 80%,rgba(192,160,96,0.15),transparent 55%),radial-gradient(ellipse at 75% 25%,rgba(160,174,184,0.08),transparent 55%),var(--jr-bg)}
.jr-hero-inner{position:relative;z-index:2;padding:0 5vw 5rem;width:100%}
.jr-hero-tag{font-family:var(--M);font-size:.6rem;letter-spacing:.25em;color:var(--jr-accent);margin-bottom:2rem}
.jr-hero h1{font-family:var(--D);font-size:clamp(5rem,14vw,14rem);line-height:.85}.jr-hero h1 span{color:var(--jr-accent)}
.jr-hero h1 em{font-style:normal;color:var(--jr-muted);font-family:var(--S);font-weight:300;display:block;font-size:.35em;margin-top:1rem;line-height:1.6;max-width:600px}
.jr-c{max-width:1200px;margin:0 auto;padding:0 5vw}.jr-s{padding:8rem 0;border-bottom:1px solid var(--jr-border)}
.jr-label{font-family:var(--M);font-size:.58rem;letter-spacing:.22em;color:var(--jr-accent);margin-bottom:1.5rem}
.jr-title{font-family:var(--D);font-size:clamp(2.8rem,6vw,6.5rem);line-height:.9;margin-bottom:2.5rem}.jr-title em{font-style:normal;color:var(--jr-muted);font-family:var(--S);font-weight:300}
.jr-body{font-size:1.1rem;line-height:1.9;color:var(--jr-muted);max-width:640px}
.jr-pillars{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--jr-border);min-height:80vh}
.jr-pill-left{position:sticky;top:0;height:100vh;display:flex;flex-direction:column;justify-content:center;padding:4rem;background:var(--jr-bg)}
.jr-pill-right{display:flex;flex-direction:column}
.jr-pill-card{background:var(--jr-bg);padding:4rem;border-bottom:1px solid var(--jr-border);min-height:50vh;display:flex;flex-direction:column;justify-content:center;position:relative;overflow:hidden}
.jr-pill-card::after{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(192,160,96,0.08),transparent 70%);opacity:0;transition:.4s;pointer-events:none}.jr-pill-card:hover::after{opacity:1}
.jr-pill-card h3{font-family:var(--D);font-size:clamp(2rem,4vw,4rem);margin-bottom:1.5rem}.jr-pill-card p{font-size:1.05rem;line-height:1.9;color:var(--jr-muted);max-width:520px}
.jr-lanes{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--jr-border);border:1px solid var(--jr-border);margin-top:3rem}
.jr-lane{background:var(--jr-bg);padding:3rem;position:relative;overflow:hidden}
.jr-lane::after{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(192,160,96,0.08),transparent 70%);opacity:0;transition:.4s;pointer-events:none}.jr-lane:hover::after{opacity:1}
.jr-lane-icon{font-size:2.5rem;margin-bottom:1rem;opacity:.3}.jr-lane h4{font-family:var(--D);font-size:1.4rem;margin-bottom:1rem}.jr-lane p{font-size:.95rem;line-height:1.8;color:var(--jr-muted)}.jr-lane code{font-family:var(--M);font-size:.5rem;color:var(--jr-accent);background:rgba(192,160,96,0.1);padding:.2rem .5rem;border-radius:3px;display:inline-block;margin-top:.8rem;word-break:break-all}
.jr-metrics{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--jr-border);margin-top:3rem}
.jr-metric{background:var(--jr-bg);padding:3rem;text-align:center;border:2px solid var(--jr-accent);position:relative;overflow:hidden}
.jr-metric::before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(192,160,96,0.1),transparent 70%)}
.jr-metric-n{font-family:var(--D);font-size:clamp(2rem,4vw,3.5rem);color:var(--jr-accent);line-height:1;position:relative}.jr-metric-l{font-family:var(--M);font-size:.5rem;letter-spacing:.15em;color:var(--jr-muted);margin-top:.8rem;position:relative;line-height:1.7}
.jr-soul{background:rgba(192,160,96,0.02);padding:10rem 0;text-align:center}
.jr-soul-q{font-family:var(--S);font-size:clamp(1.15rem,2vw,1.7rem);line-height:2;color:var(--jr-muted);max-width:780px;margin:0 auto;font-weight:300}.jr-soul-q strong{color:var(--jr-white);font-weight:500}
.jr-gallery{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--jr-border)}.jr-gal-item{background:var(--jr-glass);aspect-ratio:4/3;display:flex;align-items:center;justify-content:center;font-family:var(--D);font-size:.7rem;letter-spacing:.12em;color:rgba(240,237,230,0.08);transition:background .3s}.jr-gal-item:hover{background:rgba(192,160,96,0.06)}
.jr-fb-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1px;background:var(--jr-border);border:1px solid var(--jr-border)}.jr-fb-card{background:var(--jr-bg);padding:2.5rem;display:flex;flex-direction:column;gap:1.2rem;position:relative;overflow:hidden}.jr-fb-card::after{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(192,160,96,0.08),transparent 70%);opacity:0;transition:.4s;pointer-events:none}.jr-fb-card:hover::after{opacity:1}
.jr-fb-q{font-size:1rem;line-height:1.85;color:var(--jr-muted);font-style:italic;flex:1}.jr-fb-n{font-family:var(--D);font-size:1.1rem}.jr-fb-r{font-family:var(--M);font-size:.5rem;letter-spacing:.18em;color:var(--jr-accent);margin-top:.15rem}
.jr-footer{padding:4rem 0 2.5rem;border-top:1px solid var(--jr-border)}.jr-footer-links{display:flex;flex-wrap:wrap;gap:2rem;margin:2rem 0 3rem}.jr-footer-link{font-family:var(--D);font-size:clamp(1.4rem,3vw,2.2rem);color:var(--jr-muted);transition:color .3s}.jr-footer-link:hover{color:var(--jr-accent)}
.jr-footer-meta{display:flex;justify-content:space-between;font-family:var(--M);font-size:.5rem;letter-spacing:.15em;color:rgba(240,237,230,0.25);padding-top:2rem;border-top:1px solid var(--jr-border)}
.jrv{opacity:0;transform:translateY(24px);transition:opacity .8s cubic-bezier(.16,1,.3,1),transform .8s cubic-bezier(.16,1,.3,1)}.jrv.vis{opacity:1;transform:translateY(0)}
@media(max-width:900px){.jr-pillars{grid-template-columns:1fr}.jr-pill-left{position:relative;height:auto;padding:3rem 2rem}.jr-pill-card{padding:3rem 2rem;min-height:auto}.jr-lanes{grid-template-columns:1fr}.jr-metrics{grid-template-columns:1fr}.jr-gallery{grid-template-columns:1fr}.jr-fb-grid{grid-template-columns:1fr}.jr-footer-meta{flex-direction:column;gap:.8rem}}
@media(max-width:540px){.jr-hero h1{font-size:clamp(3.5rem,16vw,8rem)}.jr-s{padding:5rem 0}.jr-soul{padding:6rem 0}}
`
const NAV = ['Core Packaging','Superfoods','Brand Guidelines','Bars','Snacks','Marketing','Management']
export default function Jars(){return(<>
<Head><meta charSet="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Jars Range — Sivnco</title><meta name="description" content="Variant symmetry — Almond & Seed Butter Jars across Glass and Plastic pipelines."/><link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/><link href="https://fonts.googleapis.com/css2?family=Doto:wght@100..900&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400;1,600&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet"/><style dangerouslySetInnerHTML={{__html:CSS}}/></Head>
<Script src="https://unpkg.com/@studio-freight/lenis@1.0.32/dist/lenis.min.js" strategy="afterInteractive"/>
<nav className="jr-nav"><Link href="/" className="jr-logo">SIVNCO<span style={{color:'var(--jr-accent)'}}>.</span></Link><Link href="/jusamazin" className="jr-back">← Case Study</Link></nav>
<div className="jr-hero"><div className="jr-hero-bg"/><div className="jr-hero-inner"><div className="jr-hero-tag">Asset Optimization / Infographic Pipelines</div><h1>Almond &amp;<br/>Seed Butter<br/><span>Jars</span><em>Managing dual material asset pipelines — Glass Jars for premium retail, Plastic Jars for fast D2C shipping.</em></h1></div></div>
<section className="jr-s" style={{padding:0,borderBottom:'none'}}><div className="jr-pillars"><div className="jr-pill-left"><div className="jr-label jrv">Strategy</div><div className="jr-title jrv">Variant<br/><em>Symmetry.</em></div><p className="jr-body jrv">Optimizing design across two distinct material constraints while maintaining absolute brand coherence.</p></div><div className="jr-pill-right">{PILLARS.map((p,i)=>(<div key={i} className="jr-pill-card jrv"><div className="jr-label">{`0${i+1}`}</div><h3>{p.h}</h3><p>{p.b}</p></div>))}</div></div></section>
<section className="jr-s"><div className="jr-c"><div className="jr-label jrv">Infrastructure</div><div className="jr-title jrv">Asset<br/><em>Matrix.</em></div><div className="jr-lanes jrv"><div className="jr-lane"><div className="jr-lane-icon">🧴</div><h4>Plastic Jar Pipeline</h4><p>Lighter D2C shipping workflows. Optimized for fast-commerce and direct delivery channels.</p><code>Folder: 1MWScNPmKCcM-TBfx3u8XprAB3XyeWgJY</code></div><div className="jr-lane"><div className="jr-lane-icon">🫙</div><h4>Glass Jar Pipeline</h4><p>Premium physical retail channels. Weight and fragility demand specialized packaging artwork.</p><code>Folder: 1zk5CayV7uhYHWrPUAvyCfhMMWyEJUBio</code></div></div><p className="jr-body jrv" style={{marginTop:'1.5rem',fontSize:'.9rem'}}>Creative Attribution: Engineered in synchronization with visual designer <strong style={{color:'var(--jr-white)'}}>Juhi Singh</strong>.</p></div></section>
<div className="jr-soul"><div className="jr-c"><div className="jr-label jrv" style={{textAlign:'center'}}>The Material Manifest</div><blockquote className="jr-soul-q jrv">&ldquo;A visual system must adapt fluidly to <strong>physical constraints</strong>. Designing for glass requires appreciation for premium weight and light refraction; designing for plastic demands <strong>immediate clarity, rugged speed</strong>, and transactional optimization.&rdquo;</blockquote></div></div>
<section className="jr-s"><div className="jr-c"><div className="jr-label jrv">Tracking</div><div className="jr-title jrv">Pipeline<br/><em>Metrics.</em></div><div className="jr-metrics jrv"><div className="jr-metric"><div className="jr-metric-n">2 Lanes</div><div className="jr-metric-l">Independent asset structures for Glass and Plastic</div></div><div className="jr-metric"><div className="jr-metric-n">100%</div><div className="jr-metric-l">Visual sync across shared production environments</div></div></div></div></section>
<section className="jr-s" style={{padding:0}}><div className="jr-gallery">{['GLASS JAR FRONT','GLASS JAR LIFESTYLE','PLASTIC JAR FRONT','PLASTIC JAR INFOGRAPHIC'].map(g=>(<div key={g} className="jr-gal-item jrv">{g}</div>))}</div></section>
<section className="jr-s"><div className="jr-c"><div className="jr-label jrv">Voices</div><div className="jr-title jrv">Feedback<br/><em>Matrix.</em></div><div className="jr-fb-grid">{FEEDBACK.map((fb,i)=>(<div key={i} className="jr-fb-card jrv"><div className="jr-fb-q">&ldquo;{fb.q}&rdquo;</div><div><div className="jr-fb-n">{fb.n}</div><div className="jr-fb-r">{fb.r}</div></div></div>))}</div></div></section>
<div className="jr-c"><div className="jr-footer"><div className="jr-label">System Vault {'>>>'}</div><div className="jr-footer-links">{NAV.map(l=>(<Link key={l} href="/jusamazin" className="jr-footer-link">{l}</Link>))}</div><div className="jr-footer-meta"><span>© 2023–2026</span><span>My Journey @ Jus&apos;Amazin</span></div></div></div>
<Script id="jr-init" strategy="lazyOnload">{`(function(){function init(){var obs=new IntersectionObserver(function(e){e.forEach(function(e){if(e.isIntersecting){e.target.classList.add('vis');obs.unobserve(e.target)}})},{threshold:.05});document.querySelectorAll('.jrv').forEach(function(e){obs.observe(e)});setTimeout(function(){document.querySelectorAll('.jrv').forEach(function(e){e.classList.add('vis')})},2000);if(window.innerWidth<=900)document.querySelectorAll('.jrv').forEach(function(e){e.classList.add('vis')})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();(function w(){if(typeof Lenis==='undefined'){setTimeout(w,80);return}try{var l=new Lenis({duration:1.2,smooth:true,smoothTouch:false});function r(t){l.raf(t);requestAnimationFrame(r)}requestAnimationFrame(r)}catch(e){}})()})();`}</Script>
</>)}
