import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'

const PILLARS = [
  {h:"Q-Commerce Engine",b:"Deploying high-impact motion graphics and rich media directly into high-velocity instant delivery channels like Blinkit and Amazon."},
  {h:"Media Synthesis",b:"Utilizing advanced video engines like VEED to generate rapid, engaging digital marketing campaigns for the Pancake Mix lines."},
  {h:"Color Space Triage",b:"Executing immediate asset debugging. Resolving critical sRGB color profile shift issues during Flipkart uploads for the Pancake Mix Berry Blast (PCMBB) 250g infographics."},
  {h:"Competitor Benchmarking",b:"Conducting regular cross-channel visual mapping and design analysis against key category players like Slurrp Farm, Lo Foods, and Yoga Bar."},
]
const FEEDBACK = [
  {n:"Jitin Munjal",r:"Co-Founder / Creative Director",q:"The rapid deployment of video content for our Blinkit push kept our listings competitive during critical sales cycles."},
  {n:"Nirmal M.",r:"E-Commerce Optimization Lead",q:"Fixing the sRGB color profile errors on the Pancake Mix infographics saved our platform launch schedule from multi-day delays."},
]
const CSS = `
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{--mk-bg:#0A0906;--mk-white:#F0EDE6;--mk-accent:#2ECC71;--mk-amber:#F39C12;--mk-muted:rgba(240,237,230,0.45);--mk-border:rgba(240,237,230,0.08);--mk-glass:rgba(240,237,230,0.03);--D:'Doto',sans-serif;--S:'Poppins',sans-serif;--M:'Space Mono',monospace}
html{scroll-behavior:smooth}body{background:var(--mk-bg);color:var(--mk-white);font-family:var(--S);overflow-x:hidden}a{color:inherit;text-decoration:none}
.mk-nav{position:fixed;top:0;left:0;right:0;z-index:100;display:flex;align-items:center;justify-content:space-between;padding:1.2rem 5vw;background:rgba(10,9,6,0.8);backdrop-filter:blur(20px);border-bottom:1px solid var(--mk-border)}
.mk-logo{font-family:var(--D);font-size:1.3rem;letter-spacing:.08em}.mk-back{font-family:var(--M);font-size:.6rem;letter-spacing:.2em;padding:.55rem 1.4rem;border:1px solid var(--mk-border);border-radius:40px;transition:.3s}.mk-back:hover{border-color:var(--mk-accent);color:var(--mk-accent)}
.mk-hero{min-height:100vh;display:flex;align-items:flex-end;position:relative;overflow:hidden;border-bottom:1px solid var(--mk-border)}
.mk-hero-bg{position:absolute;inset:0;background:radial-gradient(ellipse at 30% 80%,rgba(46,204,113,0.15),transparent 55%),radial-gradient(ellipse at 75% 25%,rgba(243,156,18,0.08),transparent 55%),var(--mk-bg);animation:mkPulse 10s ease-in-out infinite}
@keyframes mkPulse{0%,100%{opacity:.85}50%{opacity:1}}
.mk-hero-inner{position:relative;z-index:2;padding:0 5vw 5rem;width:100%}
.mk-hero-tag{font-family:var(--M);font-size:.6rem;letter-spacing:.25em;color:var(--mk-accent);margin-bottom:2rem}
.mk-hero h1{font-family:var(--D);font-size:clamp(4.5rem,13vw,13rem);line-height:.85}.mk-hero h1 span{color:var(--mk-accent)}
.mk-hero h1 em{font-style:normal;color:var(--mk-muted);font-family:var(--S);font-weight:300;display:block;font-size:.32em;margin-top:1rem;line-height:1.6;max-width:580px}
.mk-c{max-width:1200px;margin:0 auto;padding:0 5vw}.mk-s{padding:8rem 0;border-bottom:1px solid var(--mk-border)}
.mk-label{font-family:var(--M);font-size:.58rem;letter-spacing:.22em;color:var(--mk-accent);margin-bottom:1.5rem}
.mk-title{font-family:var(--D);font-size:clamp(2.8rem,6vw,6.5rem);line-height:.9;margin-bottom:2.5rem}.mk-title em{font-style:normal;color:var(--mk-muted);font-family:var(--S);font-weight:300}
.mk-body{font-size:1.1rem;line-height:1.9;color:var(--mk-muted);max-width:640px}
.mk-pillars{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--mk-border);min-height:80vh}
.mk-pill-left{position:sticky;top:0;height:100vh;display:flex;flex-direction:column;justify-content:center;padding:4rem;background:var(--mk-bg)}
.mk-pill-right{display:flex;flex-direction:column}
.mk-pill-card{background:var(--mk-bg);padding:4rem;border-bottom:1px solid var(--mk-border);min-height:50vh;display:flex;flex-direction:column;justify-content:center;position:relative;overflow:hidden}
.mk-pill-card::after{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(46,204,113,0.08),transparent 70%);opacity:0;transition:.4s;pointer-events:none}.mk-pill-card:hover::after{opacity:1}
.mk-pill-card h3{font-family:var(--D);font-size:clamp(2rem,4vw,4rem);margin-bottom:1.5rem}.mk-pill-card p{font-size:1.05rem;line-height:1.9;color:var(--mk-muted);max-width:520px}
.mk-timeline{display:flex;flex-direction:column;gap:1px;background:var(--mk-border);border:1px solid var(--mk-border);margin-top:3rem;font-family:var(--M)}
.mk-tl-item{background:var(--mk-bg);padding:2rem 2.5rem;display:grid;grid-template-columns:120px 1fr auto;gap:2rem;align-items:center;position:relative;overflow:hidden;font-size:.85rem}
.mk-tl-item::after{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(46,204,113,0.06),transparent 70%);opacity:0;transition:.4s;pointer-events:none}.mk-tl-item:hover::after{opacity:1}
.mk-tl-chan{font-size:.5rem;letter-spacing:.18em;color:var(--mk-accent)}.mk-tl-desc{color:var(--mk-muted);line-height:1.6}.mk-tl-status{font-size:.5rem;letter-spacing:.15em;color:var(--mk-amber);background:rgba(243,156,18,0.1);padding:.3rem .8rem;border-radius:20px;white-space:nowrap}
.mk-metrics{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--mk-border);margin-top:3rem}
.mk-metric{background:var(--mk-bg);padding:3rem;text-align:center;border:2px solid var(--mk-accent);position:relative;overflow:hidden}
.mk-metric::before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(46,204,113,0.1),transparent 70%)}
.mk-metric-n{font-family:var(--D);font-size:clamp(2.5rem,5vw,4.5rem);color:var(--mk-accent);line-height:1;position:relative}.mk-metric-l{font-family:var(--M);font-size:.5rem;letter-spacing:.15em;color:var(--mk-muted);margin-top:.8rem;position:relative;line-height:1.7}
.mk-soul{background:rgba(46,204,113,0.02);padding:10rem 0;text-align:center}
.mk-soul-q{font-family:var(--S);font-size:clamp(1.15rem,2vw,1.7rem);line-height:2;color:var(--mk-muted);max-width:780px;margin:0 auto;font-weight:300}.mk-soul-q strong{color:var(--mk-white);font-weight:500}
.mk-gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--mk-border)}.mk-gal-item{background:var(--mk-glass);aspect-ratio:4/3;display:flex;align-items:center;justify-content:center;font-family:var(--D);font-size:.7rem;letter-spacing:.12em;color:rgba(240,237,230,0.08);transition:background .3s}.mk-gal-item:hover{background:rgba(46,204,113,0.06)}
.mk-fb-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1px;background:var(--mk-border);border:1px solid var(--mk-border)}.mk-fb-card{background:var(--mk-bg);padding:2.5rem;display:flex;flex-direction:column;gap:1.2rem;position:relative;overflow:hidden}.mk-fb-card::after{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 0%,rgba(46,204,113,0.08),transparent 70%);opacity:0;transition:.4s;pointer-events:none}.mk-fb-card:hover::after{opacity:1}
.mk-fb-q{font-size:1rem;line-height:1.85;color:var(--mk-muted);font-style:italic;flex:1}.mk-fb-n{font-family:var(--D);font-size:1.1rem}.mk-fb-r{font-family:var(--M);font-size:.5rem;letter-spacing:.18em;color:var(--mk-accent);margin-top:.15rem}
.mk-footer{padding:4rem 0 2.5rem;border-top:1px solid var(--mk-border)}.mk-footer-links{display:flex;flex-wrap:wrap;gap:2rem;margin:2rem 0 3rem}.mk-footer-link{font-family:var(--D);font-size:clamp(1.4rem,3vw,2.2rem);color:var(--mk-muted);transition:color .3s}.mk-footer-link:hover{color:var(--mk-accent)}
.mk-footer-meta{display:flex;justify-content:space-between;font-family:var(--M);font-size:.5rem;letter-spacing:.15em;color:rgba(240,237,230,0.25);padding-top:2rem;border-top:1px solid var(--mk-border)}
.mkv{opacity:0;transform:translateY(24px);transition:opacity .8s cubic-bezier(.16,1,.3,1),transform .8s cubic-bezier(.16,1,.3,1)}.mkv.vis{opacity:1;transform:translateY(0)}
@media(max-width:900px){.mk-pillars{grid-template-columns:1fr}.mk-pill-left{position:relative;height:auto;padding:3rem 2rem}.mk-pill-card{padding:3rem 2rem;min-height:auto}.mk-tl-item{grid-template-columns:1fr;gap:.8rem}.mk-metrics{grid-template-columns:1fr}.mk-gallery{grid-template-columns:1fr 1fr}.mk-fb-grid{grid-template-columns:1fr}.mk-footer-meta{flex-direction:column;gap:.8rem}}
@media(max-width:540px){.mk-hero h1{font-size:clamp(3rem,14vw,7rem)}.mk-s{padding:5rem 0}.mk-soul{padding:6rem 0}.mk-gallery{grid-template-columns:1fr}}
`
const NAV = ['Core Packaging','Superfoods','Brand Guidelines','Bars','Jars','Snacks','Management']
export default function Marketing(){return(<>
<Head><meta charSet="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Marketing & Digital — Sivnco</title><meta name="description" content="Multimedia workspace — quick-commerce video engine, color triage, competitor benchmarking."/><link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/><link href="https://fonts.googleapis.com/css2?family=Doto:wght@100..900&family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400;1,600&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet"/><style dangerouslySetInnerHTML={{__html:CSS}}/></Head>
<Script src="https://unpkg.com/@studio-freight/lenis@1.0.32/dist/lenis.min.js" strategy="afterInteractive"/>
<nav className="mk-nav"><Link href="/" className="mk-logo">SIVNCO<span style={{color:'var(--mk-accent)'}}>.</span></Link><Link href="/jusamazin" className="mk-back">← Case Study</Link></nav>
<div className="mk-hero"><div className="mk-hero-bg"/><div className="mk-hero-inner"><div className="mk-hero-tag">Omnichannel Deployment / Media Synthesis</div><h1><span>Marketing</span><br/>&amp; Digital<em>High-fidelity motion design for Blinkit & Amazon. Synthetic media, rapid experimentation, and color space triage.</em></h1></div></div>
<section className="mk-s" style={{padding:0,borderBottom:'none'}}><div className="mk-pillars"><div className="mk-pill-left"><div className="mk-label mkv">Strategy</div><div className="mk-title mkv">Multimedia<br/><em>Workspace.</em></div><p className="mk-body mkv">The rapid experimentation engine powering digital asset deployment across every commerce channel.</p></div><div className="mk-pill-right">{PILLARS.map((p,i)=>(<div key={i} className="mk-pill-card mkv"><div className="mk-label">{`0${i+1}`}</div><h3>{p.h}</h3><p>{p.b}</p></div>))}</div></div></section>
<section className="mk-s"><div className="mk-c"><div className="mk-label mkv">Workflow</div><div className="mk-title mkv">Campaign<br/><em>Timeline.</em></div><div className="mk-timeline mkv"><div className="mk-tl-item"><div className="mk-tl-chan">BLINKIT</div><div className="mk-tl-desc">Pancake Mix video content production via VEED engine</div><div className="mk-tl-status">DEPLOYED</div></div><div className="mk-tl-item"><div className="mk-tl-chan">AMAZON</div><div className="mk-tl-desc">E-commerce listing updates and catalog enrichment</div><div className="mk-tl-status">DEPLOYED</div></div><div className="mk-tl-item"><div className="mk-tl-chan">FLIPKART</div><div className="mk-tl-desc">sRGB color profile triage for PCMBB 250g infographics</div><div className="mk-tl-status">RESOLVED</div></div></div></div></section>
<div className="mk-soul"><div className="mk-c"><div className="mk-label mkv" style={{textAlign:'center'}}>The Digital Imperative</div><blockquote className="mk-soul-q mkv">&ldquo;A packaging file is only half the battle. In quick-commerce, your <strong>digital asset triage</strong> must be just as precise as your print setups. If an infographic shifts color on a phone screen, the <strong>brand experience breaks instantly</strong>.&rdquo;</blockquote></div></div>
<section className="mk-s"><div className="mk-c"><div className="mk-label mkv">Tracking</div><div className="mk-title mkv">Asset<br/><em>Metrics.</em></div><div className="mk-metrics mkv"><div className="mk-metric"><div className="mk-metric-n">3</div><div className="mk-metric-l">Competitors benchmarked: Slurrp Farm, Lo Foods, Yoga Bar</div></div><div className="mk-metric"><div className="mk-metric-n">25+</div><div className="mk-metric-l">E-commerce listings optimized across distribution networks</div></div></div></div></section>
<section className="mk-s" style={{padding:0}}><div className="mk-gallery">{['VIDEO TIMELINE','COLOR TRIAGE MAP','AMAZON LISTING','BLINKIT BANNER','COMPETITOR MATRIX','FINAL ASSET'].map(g=>(<div key={g} className="mk-gal-item mkv">{g}</div>))}</div></section>
<section className="mk-s"><div className="mk-c"><div className="mk-label mkv">Voices</div><div className="mk-title mkv">Feedback<br/><em>Matrix.</em></div><div className="mk-fb-grid">{FEEDBACK.map((fb,i)=>(<div key={i} className="mk-fb-card mkv"><div className="mk-fb-q">&ldquo;{fb.q}&rdquo;</div><div><div className="mk-fb-n">{fb.n}</div><div className="mk-fb-r">{fb.r}</div></div></div>))}</div></div></section>
<div className="mk-c"><div className="mk-footer"><div className="mk-label">System Telemetry {'>>>'}</div><div className="mk-footer-links">{NAV.map(l=>(<Link key={l} href="/jusamazin" className="mk-footer-link">{l}</Link>))}</div><div className="mk-footer-meta"><span>© 2023–2026</span><span>My Journey @ Jus&apos;Amazin</span></div></div></div>
<Script id="mk-init" strategy="lazyOnload">{`(function(){function init(){var obs=new IntersectionObserver(function(e){e.forEach(function(e){if(e.isIntersecting){e.target.classList.add('vis');obs.unobserve(e.target)}})},{threshold:.05});document.querySelectorAll('.mkv').forEach(function(e){obs.observe(e)});setTimeout(function(){document.querySelectorAll('.mkv').forEach(function(e){e.classList.add('vis')})},2000);if(window.innerWidth<=900)document.querySelectorAll('.mkv').forEach(function(e){e.classList.add('vis')})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();(function w(){if(typeof Lenis==='undefined'){setTimeout(w,80);return}try{var l=new Lenis({duration:1.2,smooth:true,smoothTouch:false});function r(t){l.raf(t);requestAnimationFrame(r)}requestAnimationFrame(r)}catch(e){}})()})();`}</Script>
</>)}
